sudo: false
dist: xenial
language: node_js
node_js: lts/*

addons:
  firefox: latest
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

script:

- if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
    npm run build && npm run test:sauce;
  else
    npm run lint && npm run build && npm test;
  fi
